name: Deploy to Azure

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'YourFireDetectionApp'
  PYTHON_VERSION: '3.9'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Configure Oryx
      run: |
        mkdir -p .config
        echo "python_version=3.9" > .config/oryx-buildsettings.txt
        echo "disable_php_detection=true" >> .config/oryx-buildsettings.txt
        
    - name: Create deployment package
      run: |
        zip -r webapp.zip . \
          -x '.git/*' \
          -x '.github/*' \
          -x '*.pyc' \
          -x '__pycache__/*'
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: webapp.zip