name: Deploy to Azure

on:
  push:
    branches: [ "main" ]  # Ensure this matches your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Match your Azure runtime

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create temp directory
      run: mkdir -p app/temp  # For your ONNX model storage

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YourFireDetectionApp'  # Same as in `az webapp list`
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .